
services:
  carshowroom_app_dev:
    image: 192.168.100.16:5000/carshowroom-project
    container_name: carshowroom_app_dev
    ports:
      - "9091:9091"  # Adjust port based on your app
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres_db:5432/carshowroom_dev
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=debug
    depends_on:
      - postgres_db
    restart: unless-stopped

  postgres_db:
    image: postgres:latest
    container_name: postgres_db_dev
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: carshowroom_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  postgres_data_dev: